# Generated by Django 5.0.3 on 2024-03-16 09:17

import django.db.models.deletion
import uuid
import youtubeApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('channel_art', models.ImageField(default='default_art.jpg', upload_to='channel/')),
                ('channel_icon', models.ImageField(default='default_icon.jpg', upload_to='profile/')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubeApp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=youtubeApp.models.channel_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubeApp.channel')),
                ('dislikes', models.ManyToManyField(related_name='video_disliked', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='video_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('visibility', models.BooleanField(choices=[(False, 'private'), (True, 'public')])),
                ('thumbnail', models.ImageField(upload_to='thumbnail/')),
                ('videofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youtubeApp.videofiles')),
            ],
        ),
    ]
